# Generated by Django 4.1.7 on 2023-04-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('pedido', models.TextField(max_length=500)),
                ('consultora', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.TextField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('publicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
