# Generated by Django 4.1.7 on 2023-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=100)),
                ('estado', models.TextField(default='Disponible', max_length=100)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
