# Generated by Django 4.1.7 on 2023-04-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
