# Generated by Django 4.1.7 on 2023-03-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0002_alter_producto_categoria_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creado_el',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
