# Generated by Django 4.1.7 on 2023-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0003_remove_producto_creado_el_remove_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('pedido', models.TextField(max_length=500)),
                ('consultora', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigoCN', models.IntegerField(max_length=7)),
                ('zona', models.CharField(max_length=100)),
            ],
        ),
    ]
