# Generated by Django 4.1.7 on 2023-04-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
