# Generated by Django 4.1.7 on 2023-04-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
