# Generated by Django 4.1.7 on 2023-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0007_delete_cliente_delete_consultora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
